### ISSUE TITLE
Multiple entities in card, what am I doing wrong?

### ISSUE THREAD

**Issue by fribse** [DarkFox/rejseplanen-card#3]
Hi there

I'm trying to use the rejseplanen card, but i get a message that I need to add an entity?

```
type: 'custom:rejseplanen-card'
entities:
 - entity: sensor.bus_mod_greve_st
 - entity: sensor.bus_mod_roskilde
 - entity: sensor.s_tog_mod_kobenhavn
 - entity: sensor.s_tog_mod_koge
max_entries: 5
```

My sensors are built like this:

```
  - platform: rejseplanen
    name: 'Bus mod Greve St.'
    stop_id: '1234'
    direction:
      - 'Hundige St.'
      - 'Greve St.'
```
